version: "3.8"
services:
  db:
    build: ./docker/db
    platform: linux/x86_64
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-store: